name: Run All

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SWI-Prolog
      uses: royratcliffe/swi-prolog-pack-cover@main
    - name: Compile solutions
      run: ${{github.workspace}}/allcmp.sh
    - name: Execute solutions
      run: ${{github.workspace}}/allfast.sh
