name: Run All

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SWI-Prolog and Fuse
      run: |
        sudo apt-add-repository ppa:swi-prolog/stable
        sudo apt update
        sudo apt install swi-prolog libfuse3-dev
    - name: Install Tup
      run: |
        cd "$(mktemp -d tup.XXX)"
        wget https://gittup.org/tup/releases/tup-v0.7.11.tar.gz
        tar xzf tup-v0.7.11.tar.gz
        cd tup-v0.7.11
        ./bootstrap.sh
        ./tup
        pwd | tee /dev/stderr >> $GITHUB_PATH
    - name: Compile solutions
      run: |
        cd ${{github.workspace}}
        ./allcmp.sh
    - name: Execute solutions
      run: ${{github.workspace}}/allfast.sh
