name: Run All

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SWI-Prolog
      run: |
        sudo apt-add-repository ppa:swi-prolog/stable
        sudo apt-get update
        sudo apt install swi-prolog
    - name: Compile solutions
      run: ${{github.workspace}}/allcmp.sh
    - name: Execute solutions
      run: ${{github.workspace}}/allfast.sh
