name: Run All

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Tup
      run: |
        cd "$(mktemp -d tup.XXX)"
        wget https://gittup.org/tup/releases/tup-v0.7.11.tar.gz
        tar xvzf tup-v0.7.11.tar.gz
        cd tup-v0.7.11
        ./bootstrap.sh
        ./tup
        pwd >> $GITHUB_PATH
    - name: Install SWI-Prolog
      run: |
        sudo apt-add-repository ppa:swi-prolog/stable
        sudo apt-get update
        sudo apt install swi-prolog
    - name: Compile solutions
      run: ${{github.workspace}}/allcmp.sh
    - name: Execute solutions
      run: ${{github.workspace}}/allfast.sh
